# Site settings
title: Bike GPS - Ride tracker app
email: admin@bikegps.app
author: Pigeoncv Kft.
description:
url: https://bikegps.goncz.app

# Build settings
permalink: :title/
sass:
  sass_dir: css

exclude:
  - readme_files
  - README.md
  - CNAME

appstoreid: 1450105816